// Recipe "scripts" that drive the cooking mini-game. The engine reads any Recipe;
// these are the hand-authored (curated) set. Arbitrary dishes can be generated by
// the AI route (/api/kitchen/recipe) into the same shape.

export type CookStep =
  | { kind: "chop"; item: string; item_en?: string; slices: number }
  | { kind: "add"; item: string; item_en?: string }
  | { kind: "stirfry"; seconds: number }
  | { kind: "season"; item: string; item_en?: string }
  | { kind: "plate"; garnish?: string; garnish_en?: string };

export type Recipe = {
  id: string;
  title_vi: string;
  title_en?: string;
  image?: { url: string };
  steps: CookStep[];
};

export const CURATED: Recipe[] = [
  {
    id: "trung-chien-ca-chua",
    title_vi: "Trứng chiên cà chua",
    title_en: "Egg & tomato",
    steps: [
      { kind: "chop", item: "cà chua", item_en: "tomato", slices: 4 },
      { kind: "add", item: "trứng", item_en: "eggs" },
      { kind: "stirfry", seconds: 8 },
      { kind: "season", item: "muối", item_en: "salt" },
      { kind: "plate", garnish: "hành lá", garnish_en: "scallion" },
    ],
  },
  {
    id: "rau-muong-xao-toi",
    title_vi: "Rau muống xào tỏi",
    title_en: "Garlic water spinach",
    steps: [
      { kind: "chop", item: "tỏi", item_en: "garlic", slices: 3 },
      { kind: "add", item: "rau muống", item_en: "water spinach" },
      { kind: "stirfry", seconds: 10 },
      { kind: "season", item: "nước mắm", item_en: "fish sauce" },
      { kind: "plate" },
    ],
  },
  {
    id: "thit-kho-tau",
    title_vi: "Thịt kho tàu",
    title_en: "Braised pork",
    steps: [
      { kind: "chop", item: "thịt ba chỉ", item_en: "pork belly", slices: 5 },
      { kind: "season", item: "nước hàng", item_en: "caramel" },
      { kind: "add", item: "trứng luộc", item_en: "boiled eggs" },
      { kind: "stirfry", seconds: 12 },
      { kind: "plate", garnish: "ớt", garnish_en: "chili" },
    ],
  },
];
